language: php

php:
  - 8.0

before_script:
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

script:
  vendor/bin/phpunit --verbose

notifications:
  email:
    on_success: never